Advisor/Models/Advisor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Advisor.Models
{
    public class Advisor
    {
        public int advisor_id { get; set; }
        public string advisor_name { get; set; }
        public string email { get; set; }
        public string office { get; set; }
        public string password { get; set; }

        public Advisor(int advisor_id) { 
            this.advisor_id = advisor_id;
        }
    }
}

Advisor/Controllers/AdvisorController.cs
using Advisor.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Configuration.Provider;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Advisor.Controllers
{
    public class AdvisorController : Controller
    {
        public ActionResult Advisor_Home()
        {
            return View();
        }
        public ActionResult AdvisorHomePage() {
            return View();
        }
        // GET: Advisor
        public ActionResult Logout()
        {
            HttpCookie authCookie = new HttpCookie("advisorData");
            authCookie.Expires = DateTime.Now.AddDays(-1);
            Response.Cookies.Add(authCookie);
            return RedirectToAction("./Login");
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult Register_Helper(FormCollection form)
        {
            String connStr = WebConfigurationManager.ConnectionStrings["Advising_System_11"].ToString();
            SqlConnection con = new SqlConnection(connStr);
            using (con)
            {
                SqlCommand cmd = new SqlCommand("dbo.Procedures_AdvisorRegistration", con);
                cmd.CommandType = CommandType.StoredProcedure;
                using (cmd)
                {
                    if (String.IsNullOrEmpty(form["advisor_name"]) || String.IsNullOrEmpty(form["password"]) || String.IsNullOrEmpty(form["email"]) || String.IsNullOrEmpty(form["office"]))
                    {
                        TempData["ErrorMessage"] = "Please fill in all the boxes.";
                        return RedirectToAction("./Register");
                    }
                    cmd.Parameters.AddWithValue("@advisor_name", form["advisor_name"]);
                    cmd.Parameters.AddWithValue("@password", form["password"]);
                    cmd.Parameters.AddWithValue("@email", form["email"]);
                    cmd.Parameters.AddWithValue("@office", form["office"]);
                    SqlParameter advisor_id = cmd.Parameters.AddWithValue("@Advisor_id", SqlDbType.Int);
                    advisor_id.Direction = ParameterDirection.Output;

                    con.Open();
                    cmd.ExecuteNonQuery();
                    TempData["SuccessMessage"] = "Done! Your ID is " + Convert.ToInt16(advisor_id.Value);
                    con.Close();
                    return RedirectToAction("./Login");
                }

            }

        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Login_Helper(FormCollection form)
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["Advising_System_11"].ConnectionString);
            using (con)
            {
                SqlCommand cmd = new SqlCommand("SELECT dbo.FN_AdvisorLogin(@advisor_Id,@password) AS bit ", con);
                cmd.CommandType = CommandType.Text;
                using (cmd)
                {
                    cmd.Parameters.AddWithValue("@advisor_Id", form["advisor_id"]);
                    cmd.Parameters.AddWithValue("@password", form["password"]);
                    con.Open();
                    cmd.ExecuteNonQuery();
                   /* if (String.IsNullOrEmpty(form["advisor_name"]) || String.IsNullOrEmpty(form["password"]) || String.IsNullOrEmpty(form["email"]) || String.IsNullOrEmpty(form["office"]))
                    {
                        TempData["ErrorMessage"] = "Please fill in all the boxes.";
                        return RedirectToAction("./Login");
                    }*/
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            bool x = Convert.ToBoolean(reader["bit"]);


                            if (x)
                            {
                                HttpCookie loginCookie = new HttpCookie("advisorCookie");
                                loginCookie["advisorId"] = form["advisor_id"];
                                Response.Cookies.Add(loginCookie);
                                con.Close();
                                return RedirectToAction("./AdvisorHomePage");

                            }
                            else
                            {
                                TempData["ErrorMessage"] = "Invalid Id or Password.";
                                con.Close();
                                return RedirectToAction("./Login");

                            }
                        }
                    }
                    return RedirectToAction("./Login");


                }
            }
        }

        //C
        public ActionResult Assigned_Students()
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["Advising_System_11"].ConnectionString);
            using (con)
            {
                HttpCookie advisorInfo = Request.Cookies["advisorCookie"];

                SqlCommand cmd = new SqlCommand("SELECT * FROM Student WHERE advisor_id=" + Convert.ToInt32(advisorInfo["advisorId"]), con);
                cmd.CommandType = CommandType.Text;
                using (cmd)
                {

                    con.Open();
                    cmd.ExecuteNonQuery();
                    List<Student> students = new List<Student>();
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read() && reader.HasRows)
                        {
                            int student_id = Convert.ToInt32(reader["student_id"]);
                            String student_name = Convert.ToString(reader["f_name"]);
                            String student_major = Convert.ToString(reader["major"]);
                            Student student = new Student(student_id, student_name);
                            students.Add(student);

                        }
                    }
                    con.Close();
                    return View("Assigned_Students", students);
                }
            }
        }
        //D
        public ActionResult Insert_Graduation_Plan()
        {
            return View();

        }
        public ActionResult Insert_Graduation_Plan_Helper(FormCollection form)
        {
            if (String.IsNullOrEmpty(form["semester_code"]) ||
                String.IsNullOrEmpty(form["expected_grad_date"]) ||
                String.IsNullOrEmpty(form["semester_credit_hours"]) || String.IsNullOrEmpty(form["student_id.student_id"]))
            {
                TempData["ErrorMessage"] = "Please fill in all the boxes.";
                return RedirectToAction("./Insert_Graduation_Plan_View");
            }

            try
            {
                if (!int.TryParse(form["student_id.student_id"], out int studentId))
                {
                    throw new ArgumentException("Invalid student_id");
                }
                if (!int.TryParse(form["semester_credit_hours"], out int semester_credit_hours))
                {
                    throw new ArgumentException("Invalid semester_credit_hours ");
                }
                if (!DateTime.TryParse(form["expected_grad_date"], out DateTime expected_grad_date))
                {
                    throw new ArgumentException("Invalid expected_grad_date");
                }
                SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["Advising_System_11"].ConnectionString);
                SqlCommand studentCheck = new SqlCommand("SELECT dbo.FN_CheckStudentExists(@Student_id) AS bit ", con);
                studentCheck.CommandType = CommandType.Text;
                studentCheck.Parameters.AddWithValue("@Student_id", studentId);

                SqlCommand semesterCheck = new SqlCommand("SELECT dbo.FN_CheckSemesterCodeExists(@semester_code) AS bit ", con);
                semesterCheck.CommandType = CommandType.Text;
                semesterCheck.Parameters.AddWithValue("@semester_code", form["semester_code"]);


                SqlCommand cmd = new SqlCommand("dbo.[Procedures_AdvisorCreateGP]", con);
                cmd.CommandType = CommandType.StoredProcedure;

                
                    con.Open();
                    studentCheck.ExecuteNonQuery();
                    SqlDataReader reader = studentCheck.ExecuteReader();
 
                    while (reader.Read())
                    {
                        bool x = Convert.ToBoolean(reader["bit"]);
                        if (!x)
                        {
                            TempData["ErrorMessage"] = "Student does not exist.";
                            con.Close();
                            return RedirectToAction("./Insert_Graduation_Plan");
                        }
                    }
                    con.Close();
                    con.Open();

                    semesterCheck.ExecuteNonQuery();
                    SqlDataReader rdr = semesterCheck.ExecuteReader();

                    while (rdr.Read())
                    {
                        bool y = Convert.ToBoolean(rdr["bit"]);
                        if (!y)
                        {
                            TempData["ErrorMessage"] = "Semester_Code does not exist.";
                            con.Close();
                            return RedirectToAction("./Insert_Graduation_Plan");
                        }
                    }
                    con.Close();



                        cmd.Parameters.AddWithValue("@student_id", studentId);
                        cmd.Parameters.AddWithValue("@Semester_code", form["semester_code"]);

Advisor/Views/Advisor/A_R_extra_credit_hours.cshtml
@model Advisor.Models.Request_Semester_Credit

@{
    ViewBag.Title = "A_R_extra_credit_hours";
}

<h2>A_R_extra_credit_hours</h2>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}
@using (Html.BeginForm("A_R_extra_credit_hours_Helper", "Advisor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Request_Semester_Credit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.semester_code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.semester_code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.semester_code, "", new { @class = "text-danger" })
        </div>
    </div>        <div class="form-group">
        @Html.LabelFor(model => model.request_id.request_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.request_id.request_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.request_id.request_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "AdvisorHomePage")
</div>

Advisor/Views/Advisor/AdvisorHomePage.cshtml
@{
    ViewBag.Title = "AdvisorHomePage";
}

<h2>AdvisorHomePage</h2>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="View Assigned_Students" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Assigned_Students';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Insert_Graduation_Plan" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Insert_Graduation_Plan';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Insert_Course_for_Graduation_Plan" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Insert_Course_for_Graduation_Plan';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Update_GP" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Update_GP';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Assigned_Students_with_their_Majors" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Assigned_Students_with_their_Majors';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Delete_Course_GP" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Delete_Course_GP';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="View_Requests" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './View_Requests';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="View_Pending_Requests" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './View_Pending_Requests';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="A_R_extra_credit_hours" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './A_R_extra_credit_hours';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="A_R_extra_course" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './A_R_extra_course';" />
    </div>
</div>
@using (Html.BeginForm("Logout", "Advisor", FormMethod.Post))
{
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Logout" class="btn btn-default btn-danger" style="margin-top: 10px; margin-bottom: 10px" />
        </div>
    </div>
}

Advisor/Views/Advisor/Advisor_Home.cshtml
@{
    ViewBag.Title = "Advisor_Home";
}

<h2>Advisor_Home</h2>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Login" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Login';" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Register" class="btn btn-default  btn-primary" style="margin-top:10px" onclick="window.location.href = './Register';" />
    </div>
</div>

Advisor/Views/Advisor/Assigned_Students.cshtml
@using Advisor.Models
@model List<Student>

@{
    ViewBag.Title = "Assigned_Students";
}

<h2>Assigned_Students</h2>
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model[0].student_id)</th>

        <th>@Html.DisplayNameFor(model => model[0].f_name)</th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.student_id)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.f_name)

            </td>

        </tr>
    }

</table>
<div>
    @Html.ActionLink("Back to List", "AdvisorHomePage")
</div>

Advisor/Views/Advisor/Assigned_Students_with_their_Majors.cshtml
@model Advisor.Models.Student

@{
    ViewBag.Title = "Assigned_Students_with_their_Majors";
}

<h2>Assigned_Students_with_their_Majors</h2>

@using (Html.BeginForm("Assigned_Students_with_their_Majors_Helper", "Advisor",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })





        <div class="form-group">
            @Html.LabelFor(model => model.major, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.major, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.major, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Select" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "AdvisorHomePage")
</div>

Advisor/Views/Advisor/Delete_Course_GP.cshtml
@model Advisor.Models.GradPlan_Student_Course

@{
    ViewBag.Title = "Delete_Course_GP";
}

<h2>Delete_Course_GP</h2>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

@using (Html.BeginForm("Delete_Course_GP_Helper", "Advisor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>GradPlan_Student_Course</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.student_id.student_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.student_id.student_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.student_id.student_id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.semester_code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.semester_code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.semester_code, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.course_id.course_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.course_id.course_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.course_id.course_id, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "AdvisorHomePage")
</div>

Advisor/Views/Advisor/Insert_Course_for_Graduation_Plan.cshtml
@model Advisor.Models.GradPlan_Course

@{
    ViewBag.Title = "Insert_Course_for_Graduation_Plan";
}

<h2>Insert_Course_for_Graduation_Plan</h2>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

@using (Html.BeginForm("Insert_Course_for_Graduation_Plan_Helper", "Advisor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>GradPlan_Course</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.student_id.student_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.student_id.student_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.student_id.student_id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.semester_code.semester_code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.semester_code.semester_code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.semester_code.semester_code, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.course_name.course_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.course_name.course_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.course_name.course_name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Insert" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "AdvisorHomePage")
</div>

Advisor/Views/Advisor/Insert_Graduation_Plan.cshtml
@model Advisor.Models.Graduation_Plan

@{
    ViewBag.Title = "Insert_Graduation_Plan";
}

<h2>Insert_Graduation_Plan</h2>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

@using (Html.BeginForm("Insert_Graduation_Plan_Helper", "Advisor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Graduation_Plan</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.student_id.student_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.student_id.student_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.student_id.student_id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.semester_code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.semester_code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.semester_code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.semester_credit_hours, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.semester_credit_hours, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.semester_credit_hours, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.expected_grad_date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.expected_grad_date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.expected_grad_date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Insert" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "AdvisorHomePage")
</div>

Advisor/Views/Advisor/Login.cshtml
@model Advisor.Models.Advisor

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@if (TempData["ErrorMessage"] != null)
{

    <div class="alert alert-success">
        @TempData["ErrorMessage"]
    </div>
}
@if (TempData["SuccessMessage"] != null)
{

    <div class="alert alert-danger">
        @TempData["SuccessMessage"]
    </div>
}

@using (Html.BeginForm("Login_Helper", "Advisor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Advisor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.advisor_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.advisor_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.advisor_id, "", new { @class = "text-danger" })
            </div>
        </div>






        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default btn-success" style="margin-top:12px" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Advisor_Home")
</div>

Advisor/Views/Advisor/Register.cshtml
@model Advisor.Models.Advisor

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>s
@if (TempData["ErrorMessage"] != null) {

    <div
    class="alert alert-danger">
    @TempData["ErrorMessage"]
    </div>
}

        @using (Html.BeginForm("Register_Helper", "Advisor", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Advisor</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.advisor_name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.advisor_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.advisor_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.office, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.office, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.office, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Register" class="btn btn-default btn-success" style="margin-top:12px" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Advisor_Home")
        </div>